- name: Install Nginx
  ansible.builtin.yum:
   name: nginx
   state: present

- name: Enable Nginx
  ansible.builtin.service:
   name: nginx
   enabled: yes

- name: Start Nginx
  ansible.builtin.service:
   name: nginx
   state: started

- name: Download Front-end Zip
  ansible.builtin.get_url:
   url: https://github.com/stans-robot-project/frontend/archive/main.zip
   dest: /tmp/frontend.zip

- name: Delete files in nginx html folder
  ansible.builtin.file:
   path: /usr/share/nginx/html
   state: absent

- name: Unzip the frontend folder
  ansible.builtin.unarchive:
   src: /tmp/frontend.zip
   dest: frontend
   remote_src: yes