- name: Copy Sql repo to repos folder of yum
  ansible.builtin.copy: 
    src: mysql.repo
    dest: /etc/yum.repos.d/    

- name: Install sql Community server
  ansible.builtin.package:
     name: mysql-community-server
     state: present


- name: enable and start the service
  ansible.builtin.include_role:
   name: common
   tasks_from: systemservice

