- name: Copy Sql repo to repos folder of yum
  ansible.builtin.copy: 
    src: mysql.repo
    dest: /etc/yum.repos.d/    

- name: Install sql Community server
  ansible.builtin.package:
     name: 
      - mysql-community-server
      - MySQL-python
     state: present


- name: enable and start the service
  ansible.builtin.include_role:
   name: common
   tasks_from: systemservice


- name: Register text present in mysqld.log
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mounts

- name: Print returned information
  ansible.builtin.set_fact:
    temp_pwd: "{{ mounts['content'] | b64decode | regex_findall('.*A temporary password is.*')| join('') | split(': ') | last}}" 

- name: print the set fact password captured
  ansible.builtin.debug:
   msg: "{{temp_pwd}}"

- name: Create database user with name 'bob' and password '12345' with all database privileges
  community.mysql.mysql_user:
    name: root
    password: "{{temp_pwd}}"
    priv: '*.*:ALL'
    state: present

