- name: Call Python module steps
  ansible.builtin.include_role: 
   name: common
   tasks_from: python

- name: copy systemd.service of {{COMPONENT}} to systemd file
  ansible.builtin.copy: 
   src: systemd.service
   dest: /etc/systemd/system/{{COMPONENT}}.service
  ignore_errors: true