- name: Download the {{COMPONENT}} Zip
  ansible.builtin.unarchive:
   src: "https://github.com/stans-robot-project/catalogue/archive/main.zip"
   dest: /tmp
   remote_src: yes

- name: Delte everything in {{USER}}/{{COMPONENT}}
  ansible.builtin.file:
   path: /home/{{USER}}/{{COMPONENT}}
   state: absent

- name: Copy the file to a new folder
  ansible.builtin.copy:
   src: /tmp/{{COMPONENT}}-main/
   dest: /home/{{USER}}/{{COMPONENT}}/
   remote_src: yes

- name: delete the old file
  ansible.builtin.file:
   path: /home/{{USER}}/{{COMPONENT}}-main
   state: absent