- name: Install filebeat public signing key
  ansible.builtin.shell: sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Template a file to /etc/filebeat/filebeat.yml
  ansible.builtin.template:
    src: filebeat.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: present

- name: Template a file to /etc/filebeat/filebeat.yml
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Enable service filebeat, and not touch the state
  ansible.builtin.service:
    name: filebeat
    enabled: yes

- name: Restart service filebeat, in all cases
  ansible.builtin.service:
    name: filebeat
    state: restarted

