- name: Template a file to /etc/filebeat/filebeat.yml
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml


- name: Restart service logstash, in all cases
  ansible.builtin.service:
    name: filebeat
    state: restarted

