- name: Install Node repo for {{COMPONENT}}
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install NOdejs for {{COMPONENT}}
  ansible.builtin.package:
   name: nodejs
   state: present

- name: Add {{USER}} user
  ansible.builtin.include_role:
    name: common
    tasks_from: adduser

- name: Add Roboshop user
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Download of {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: NPM Install of {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: npminstall

- name: DNS update {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: dnsupdate

- name: System service {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemservice

- name: filebeat for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: filebeat

- name: rsyslog for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: rsyslog