- name: Template a file to /etc/rsyslog.d/rsyslog.conf
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf


- name: Restart service rsyslog, in all cases
  ansible.builtin.service:
    name:  rsyslog
    state: restarted