- name: copy systemd.service of {{COMPONENT}} to systemd file
  ansible.builtin.copy: 
   src: /home/{{USER}}/{{COMPONENT}}/systemd.service
   dest: /etc/systemd/system/{{COMPONENT}}.service
   remote_src: yes
   ignore_errors: True

- name: Enable service {{COMPONENT}}, and not touch the state
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: yes
    name: "{{COMPONENT}}"
