- name: copy systemd.service of {{COMPONENT}} to systemd file
  ansible.builtin.template: 
   src: systemd.service
   dest: /etc/systemd/system/{{COMPONENT}}.service
  ignore_errors: true

- name: Enable service {{COMPONENT}}, and not touch the state
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: yes
    name: "{{COMPONENT}}"
