- name: Download mongodb repo
  ansible.builtin.get_url:
   url: https://raw.githubusercontent.com/stans-robot-project/mongodb/main/mongo.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
   name: mongodb-org
   state: present

- name: replace the IP with 0.0.0.0
  ansible.builtin.replace:
   path: /etc/mongod.conf
   regexp: '127.0.0.1'
   replace: '0.0.0.0'

- name: Enable mongo service
  ansible.builtin.service:
   name: mongod
   enabled: yes
- name: start mongod service
  ansible.builtin.service:
   name: mongod
   state: started

- name: Download app repos
  ansible.builtin.unarchive:
   url: https://github.com/stans-robot-project/mongodb/archive/main.zip
   dest: /tmp/
   remote_src: yes

- name: load the schems
  community.mongodb.mongodb_shell:
   file: /tmp/mongodb-main/{{list}}.js
   idempotent: yes
   loop:
    - catalogue
    - users
   