- name: Playbook1
  hosts: all
  vars_files: vals.yaml
   
  vars:
   URL: www.global.com
  
  vars_prompt:
   - name: PURL
     prompt: What is your URL
     private: false

  tasks:
   - name: This task is to print local variable
     vars:
      URL: www.google.com
     ansible.builtin.debug:
      msg: "{{URL}}"

   - name: This is to print global value
     ansible.builtin.debug:
       msg: "{{URL}}"
     tags: front-end

   - name: This is prompt URL
     ansible.builtin.debug: 
       msg: "{{PURL}}"
     tags: back-end
     

   - name: This is CLI URL
     ansible.builtin.debug:
       msg: "{{CMsD_URL}}" 
     ignore_errors: yes
     tags: front-end

   - name: This is file URL
     ansible.builtin.debug:
       msg: "{{SEP_URL}}"

   - name: NAme of Distribution is 
     ansible.builtin.debug:
       msg: "{{ansible_distribution}}"
     when:
      ansible_distribution == "CentOS"
     tags: back-end
     
    
   - name: This is for loop
     ansible.builtin.debug:
       msg: "{{item}}"
     loop:
        - 1
        - 2
        - 3
        - Hello

   - name: Execute shell and register
     ansible.builtin.shell: uptime
     register: output

   - name: Print the previous output
     ansible.builtin.debug:
      msg: "{{output.rc}}"
     
   - name: Print the previous output
     ansible.builtin.debug:
      msg: "{{output.msg}}"
    
   - name: set fact 
     set_fact:
      msg: "Hello World"
      nonmg: "niyavva"

   - name: display fact
     ansible.builtin.debug:
      msg: "{{msg}}"

   - name: Install Nginx on the server
     ansible.builtin.package:
      name: Nginx
      state: present

    - name: Add a file on the server
      ansible.debug.shell: cat hello.txt
  
    - name: copy a file
      ansible.debug.copy: 
       src: hello.txt
       dest: folder/