- name: This is play1
  hosts: all

  vars_files: vals.yaml
  vars_prompt:
   - name: PURL
     prompt: enter the URL
     private: false
  
  vars:
    URL: play.google.com
  
  tasks:
   - name: printing url task
     ansible.builtin.debug:
      msg: value of this is {{URL}}

   - name: printing CMD LINE variable
     ansible.builtin.debug:
      msg: value of this is {{CMD_URL}}
    
   - name: enter the local variable value
     vars:
      URL: Helloworld.org.com
     ansible.builtin.debug:
      msg: "{{URL}}" 
  
  tasks:
   - name: printing the value from aonther file
     ansible.builtin.debug:
      msg: The value from another file is {{SEP_URL}}