- name: Demo using variables
  hosts: all
  
  vars:
    URL: play.google.com
  
  tasks:
   - name: printing url task
     ansible.builtin.debug:
      msg: value of this is {{URL}}

   - name: printing local variable
     vars:
      URL: tatasky.net
     ansible.builtin.debug:
      msg: value of this is {{URL}}
    
