- name: Playbook1
  hosts: all
  vars_files: vals.yaml
   
  vars:
   URL: www.global.com
  
  vars_prompt:
   - name: PURL
     prompt: What is your URL
     private: false

  tasks:
   - name: This task is to print local variable
     vars:
      URL: www.google.com
     ansible.bulitin.debug:
      msg: "{{URL}}"

   - name: This is to print global value
      ansible.bulitin.debug:
       msg: "{{URL}}"

   - name: This is prompt URL
      ansible.builtin.debug: 
       msg: "{{PURL}}"

   - name: This is CLI URL
      ansible.builtin.debug:
       msg: "{{C_URL}}"
    
   - name: This is file URL
      ansible.builtin.debug:
       msg: "{{SEP_URL}}"