- name: Demo using variables
  hosts: all
  
  vars:
    URL: play.google.com
  
  tasks:
   - name: printing url task
     ansible.builtin.debug:
      msg: value of this is {{URL}}

   - name: printing local variable
     ansible.builtin.debug:
      msg: value of this is {{URL}}
     vars:
      URL: tatasky.net

   - name: priting the value from command line
     ansible.builtin.debug:
      msg: value of CLI is {{CMD_URL}}
    
