- name: This is play1
  hosts: all
  
  vars:
    URL: play.google.com
  
  tasks:
   - name: printing url task
     ansible.builtin.debug:
      msg: value of this is {{URL}}

   - name: printing local variable
     ansible.builtin.debug:
      msg: value of this is {{URL}}
     vars:
      URL: tatasky.net

   - name: priting the value from command line
     vars:
      CMD_URL: abc.sdsd.33
     ansible.builtin.debug:
       msg: value of CLI is {{CMD_URL}}
    
