- name: This is play1
  hosts: all
  
  vars:
    URL: play.google.com
  
  tasks:
   - name: printing url task
     ansible.builtin.debug:
      msg: value of this is {{URL}}

   - name: printing local variable
     ansible.builtin.debug:
      msg: value of this is {{CMD_URL}}